"""Type stubs for the untyped PyObjC symbols re-exported by ``pyobjc_typings.py``.

Type checkers prefer this ``.pyi`` over the runtime ``.py`` module, so the
classes/constants below describe only the surface this project uses. None of
this exists at runtime — the real objects come from PyObjC framework modules.
"""

from collections.abc import Callable, Mapping, Sequence
from types import TracebackType
from typing import Literal, Protocol, TypeAlias, TypedDict
from typing_extensions import deprecated

AXAction: TypeAlias = str
AXAttribute: TypeAlias = str
AXError: TypeAlias = int
AXRole: TypeAlias = str
FourCharCode: TypeAlias = int
NSComparisonResult: TypeAlias = Literal[-1, 0, 1]
NSRunLoopMode: TypeAlias = str
NSTimeInterval: TypeAlias = float
NSWorkspaceLaunchIdentifier: TypeAlias = int

class AXUIElement:
    """Opaque ``AXUIElementRef`` handle produced and consumed by the AX APIs."""

class CFRunLoop:
    """Opaque ``CFRunLoopRef`` handle returned by ``NSRunLoop.getCFRunLoop``."""

class ObjCSelector(Protocol):
    """PyObjC ``objc.selector`` wrapper (e.g. the return of ``endSheetMethod``)."""

    selector: bytes
    signature: bytes
    callable: Callable[..., object]

class NSRange(Protocol):
    location: int
    length: int

class NSValue(Protocol):
    def rangeValue(self) -> NSRange: ...

class NSData(Protocol):
    def length(self) -> int: ...
    def bytes(self) -> memoryview: ...

class NSLocale(Protocol):
    @classmethod
    def currentLocale(cls) -> NSLocale: ...
    def localeIdentifier(self) -> str: ...

class NSError(Protocol):
    def domain(self) -> str: ...
    def code(self) -> int: ...
    def localizedDescription(self) -> str: ...
    def localizedFailureReason(self) -> str | None: ...
    def localizedRecoverySuggestion(self) -> str | None: ...
    def userInfo(self) -> Mapping[str, object]: ...

class NSAppleEventError(TypedDict, total=False):
    """Error dictionary produced by ``NSAppleScript`` compile/execute failures."""

    NSAppleScriptErrorMessage: str
    NSAppleScriptErrorBriefMessage: str
    NSAppleScriptErrorNumber: int
    NSAppleScriptErrorAppName: str
    NSAppleScriptErrorRange: NSValue

class NSWorkspaceApplicationInfo(TypedDict, total=False):
    """Entries of ``NSWorkspace.activeApplication``/``launchedApplications``."""

    NSApplicationBundleIdentifier: str
    NSApplicationName: str
    NSApplicationPath: str
    NSApplicationProcessIdentifier: int
    NSApplicationProcessSerialNumberHigh: int
    NSApplicationProcessSerialNumberLow: int
    NSWorkspaceApplicationKey: NSRunningApplication

class UTType(Protocol):
    """UniformTypeIdentifiers ``UTType`` (content-type descriptor)."""

    @classmethod
    def typeWithIdentifier_(cls, identifier: str) -> UTType | None: ...
    @classmethod
    def typeWithFilenameExtension_(cls, filename_extension: str) -> UTType | None: ...
    @classmethod
    def typeWithMIMEType_(cls, mime_type: str) -> UTType | None: ...
    def identifier(self) -> str: ...
    def preferredFilenameExtension(self) -> str | None: ...
    def preferredMIMEType(self) -> str | None: ...
    def localizedDescription(self) -> str | None: ...
    def isDynamic(self) -> bool: ...
    def isDeclared(self) -> bool: ...
    def isPublicType(self) -> bool: ...
    def conformsToType_(self, other: UTType) -> bool: ...

# PyObjC framework modules re-exported by the runtime shim. They resolve their
# attributes dynamically via module-level ``__getattr__``; the module protocols
# (defined at the bottom of this stub) describe the exact surface pulled from
# each of them.
AppKit: AppKitModule
ApplicationServices: ApplicationServicesModule
Foundation: FoundationModule
AppHelper: AppHelperModule
objc: ObjcModule

# --- objc classes/functions ---
class autorelease_pool:
    def __enter__(self) -> None: ...
    def __exit__(
        self, exc_type: type[BaseException] | None, value: BaseException | None, tp: TracebackType | None
    ) -> None: ...

# --- Foundation constants/classes ---
NSDefaultRunLoopMode: Literal["kCFRunLoopDefaultMode"]
NSRunLoopCommonModes: Literal["kCFRunLoopCommonModes"]

class NSDate:
    @classmethod
    def alloc(cls) -> NSDate: ...
    def init(self) -> NSDate: ...
    @classmethod
    def date(cls) -> NSDate: ...
    @classmethod
    def now(cls) -> NSDate: ...
    @classmethod
    def distantFuture(cls) -> NSDate: ...
    @classmethod
    def distantPast(cls) -> NSDate: ...
    @classmethod
    def dateWithTimeIntervalSinceNow_(cls, seconds: NSTimeInterval) -> NSDate: ...
    @classmethod
    def dateWithTimeIntervalSince1970_(cls, seconds: NSTimeInterval) -> NSDate: ...
    @classmethod
    def dateWithTimeInterval_sinceDate_(cls, seconds: NSTimeInterval, date: NSDate) -> NSDate: ...
    @classmethod
    def timeIntervalSinceReferenceDate(cls) -> NSTimeInterval: ...
    def initWithTimeIntervalSinceNow_(self, seconds: NSTimeInterval) -> NSDate: ...
    def initWithTimeIntervalSince1970_(self, seconds: NSTimeInterval) -> NSDate: ...
    def initWithTimeInterval_sinceDate_(self, seconds: NSTimeInterval, date: NSDate) -> NSDate: ...
    def timeIntervalSinceNow(self) -> NSTimeInterval: ...
    def timeIntervalSince1970(self) -> NSTimeInterval: ...
    def timeIntervalSinceDate_(self, date: NSDate) -> NSTimeInterval: ...
    def compare_(self, other: NSDate) -> NSComparisonResult: ...
    def earlierDate_(self, other: NSDate) -> NSDate: ...
    def laterDate_(self, other: NSDate) -> NSDate: ...
    def isEqualToDate_(self, other: NSDate) -> bool: ...
    def description(self) -> str: ...
    def descriptionWithLocale_(self, locale: NSLocale | None) -> str: ...
    def addTimeInterval_(self, seconds: NSTimeInterval) -> NSDate: ...

class NSURL:
    @classmethod
    def URLWithString_(cls, string: str) -> NSURL | None: ...
    @classmethod
    def URLWithString_relativeToURL_(cls, string: str, base_url: NSURL | None) -> NSURL | None: ...
    @classmethod
    def fileURLWithPath_(cls, path: str) -> NSURL: ...
    @classmethod
    def fileURLWithPath_isDirectory_(cls, path: str, is_directory: bool) -> NSURL: ...
    def absoluteString(self) -> str | None: ...
    def path(self) -> str | None: ...
    def isFileURL(self) -> bool: ...
    def scheme(self) -> str | None: ...
    def host(self) -> str | None: ...
    def lastPathComponent(self) -> str | None: ...
    def URLByAppendingPathComponent_(self, path_component: str) -> NSURL: ...

class NSAppleEventDescriptor:
    def stringValue(self) -> str | None: ...
    def int32Value(self) -> int: ...
    def booleanValue(self) -> bool: ...
    def descriptorType(self) -> FourCharCode: ...
    def numberOfItems(self) -> int: ...
    def descriptorAtIndex_(self, index: int) -> NSAppleEventDescriptor | None: ...
    def descriptorForKeyword_(self, keyword: FourCharCode) -> NSAppleEventDescriptor | None: ...
    def enumCodeValue(self) -> FourCharCode: ...
    def data(self) -> NSData: ...

class NSAppleScript:
    @classmethod
    def alloc(cls) -> NSAppleScript: ...
    def initWithSource_(self, source: str) -> NSAppleScript: ...
    def source(self) -> str | None: ...
    def compileAndReturnError_(self, error: None) -> tuple[bool, NSAppleEventError | None]: ...
    def isCompiled(self) -> bool: ...
    def executeAndReturnError_(self, error: None) -> tuple[NSAppleEventDescriptor | None, NSAppleEventError | None]: ...

class NSBundle:
    @classmethod
    def mainBundle(cls) -> NSBundle: ...
    @classmethod
    def bundleWithPath_(cls, path: str) -> NSBundle | None: ...
    @classmethod
    def bundleWithURL_(cls, url: NSURL) -> NSBundle | None: ...
    def bundlePath(self) -> str: ...
    def bundleURL(self) -> NSURL: ...
    def bundleIdentifier(self) -> str | None: ...
    def executablePath(self) -> str | None: ...
    def executableURL(self) -> NSURL | None: ...
    def pathForResource_ofType_(self, name: str | None, extension: str | None) -> str | None: ...
    def URLForResource_withExtension_(self, name: str | None, extension: str | None) -> NSURL | None: ...
    def infoDictionary(self) -> Mapping[str, object] | None: ...
    def objectForInfoDictionaryKey_(self, key: str) -> object: ...

class NSTimer:
    @classmethod
    def alloc(cls) -> NSTimer: ...
    @classmethod
    def timerWithTimeInterval_target_selector_userInfo_repeats_(
        cls, interval: NSTimeInterval, target: object, selector: str | bytes, user_info: object, repeats: bool
    ) -> NSTimer: ...
    @classmethod
    def timerWithTimeInterval_repeats_block_(
        cls, interval: NSTimeInterval, repeats: bool, block: Callable[[NSTimer], None]
    ) -> NSTimer: ...
    @classmethod
    def scheduledTimerWithTimeInterval_target_selector_userInfo_repeats_(
        cls, interval: NSTimeInterval, target: object, selector: str | bytes, user_info: object, repeats: bool
    ) -> NSTimer: ...
    @classmethod
    def scheduledTimerWithTimeInterval_repeats_block_(
        cls, interval: NSTimeInterval, repeats: bool, block: Callable[[NSTimer], None]
    ) -> NSTimer: ...
    def initWithFireDate_interval_target_selector_userInfo_repeats_(
        self,
        fire_date: NSDate,
        interval: NSTimeInterval,
        target: object,
        selector: str | bytes,
        user_info: object,
        repeats: bool,
    ) -> NSTimer: ...
    def initWithFireDate_interval_repeats_block_(
        self, fire_date: NSDate, interval: NSTimeInterval, repeats: bool, block: Callable[[NSTimer], None]
    ) -> NSTimer: ...
    def fire(self) -> None: ...
    def fireDate(self) -> NSDate: ...
    def setFireDate_(self, fire_date: NSDate) -> None: ...
    def timeInterval(self) -> NSTimeInterval: ...
    def tolerance(self) -> NSTimeInterval: ...
    def setTolerance_(self, tolerance: NSTimeInterval) -> None: ...
    def invalidate(self) -> None: ...
    def isValid(self) -> bool: ...
    def userInfo(self) -> object: ...

class NSPort:
    @classmethod
    def port(cls) -> NSPort: ...
    @classmethod
    def alloc(cls) -> NSPort: ...
    def init(self) -> NSPort: ...
    def invalidate(self) -> None: ...
    def isValid(self) -> bool: ...
    def delegate(self) -> object: ...
    def setDelegate_(self, delegate: object) -> None: ...
    def scheduleInRunLoop_forMode_(self, run_loop: NSRunLoop, mode: NSRunLoopMode) -> None: ...
    def removeFromRunLoop_forMode_(self, run_loop: NSRunLoop, mode: NSRunLoopMode) -> None: ...
    def reservedSpaceLength(self) -> int: ...

class NSRunLoop:
    @classmethod
    def currentRunLoop(cls) -> NSRunLoop: ...
    @classmethod
    def mainRunLoop(cls) -> NSRunLoop: ...
    def currentMode(self) -> NSRunLoopMode | None: ...
    def getCFRunLoop(self) -> CFRunLoop: ...
    def limitDateForMode_(self, mode: NSRunLoopMode) -> NSDate | None: ...
    def addTimer_forMode_(self, timer: NSTimer, mode: NSRunLoopMode) -> None: ...
    def addPort_forMode_(self, port: NSPort, mode: NSRunLoopMode) -> None: ...
    def removePort_forMode_(self, port: NSPort, mode: NSRunLoopMode) -> None: ...
    def configureAsServer(self) -> None: ...
    def run(self) -> None: ...
    def runUntilDate_(self, limit_date: NSDate) -> None: ...
    def runMode_beforeDate_(self, mode: NSRunLoopMode, limit_date: NSDate) -> bool: ...
    def acceptInputForMode_beforeDate_(self, mode: NSRunLoopMode, limit_date: NSDate) -> None: ...
    def performBlock_(self, block: Callable[[], None]) -> None: ...
    def performInModes_block_(self, modes: Sequence[NSRunLoopMode], block: Callable[[], None]) -> None: ...
    def performSelector_target_argument_order_modes_(
        self, selector: str | ObjCSelector, target: object, argument: object, order: int, modes: Sequence[NSRunLoopMode]
    ) -> None: ...
    def cancelPerformSelector_target_argument_(self, selector: str, target: object, argument: object) -> None: ...
    def cancelPerformSelectorsWithTarget_(self, target: object) -> None: ...

class AppHelperModule(Protocol):
    def callAfter(self, func: Callable[..., object], *args: object, **kwargs: object) -> None: ...
    def callLater(
        self, delay: NSTimeInterval, func: Callable[..., object], *args: object, **kwargs: object
    ) -> None: ...
    def endSheetMethod(self, method: Callable[..., object]) -> ObjCSelector: ...
    def stopEventLoop(self) -> bool: ...
    def runConsoleEventLoop(
        self,
        argv: Sequence[str] | None = None,
        installInterrupt: bool = False,
        mode: NSRunLoopMode = NSDefaultRunLoopMode,
        maxTimeout: NSTimeInterval = 3.0,
    ) -> None: ...
    def runEventLoop(
        self,
        argv: Sequence[str] | None = None,
        unexpectedErrorAlert: Callable[[], bool] | None = None,
        installInterrupt: bool | None = None,
        pdb: bool | None = None,
        main: Callable[[Sequence[str]], int] = ...,
    ) -> None: ...

def callAfter(func: Callable[..., object], *args: object, **kwargs: object) -> None: ...
def callLater(delay: NSTimeInterval, func: Callable[..., object], *args: object, **kwargs: object) -> None: ...
def endSheetMethod(method: Callable[..., object]) -> ObjCSelector: ...
def stopEventLoop() -> bool: ...
def runConsoleEventLoop(
    argv: Sequence[str] | None = None,
    installInterrupt: bool = False,
    mode: NSRunLoopMode = NSDefaultRunLoopMode,
    maxTimeout: NSTimeInterval = 3.0,
) -> None: ...
def runEventLoop(
    argv: Sequence[str] | None = None,
    unexpectedErrorAlert: Callable[[], bool] | None = None,
    installInterrupt: bool | None = None,
    pdb: bool | None = None,
    main: Callable[[Sequence[str]], int] = ...,
) -> None: ...

# --- AppKit constants/classes ---
NSApplicationActivateAllWindows: Literal[1]
NSApplicationActivateIgnoringOtherApps: Literal[2]

NSWorkspaceLaunchAndPrint: Literal[2]
NSWorkspaceLaunchWithErrorPresentation: Literal[64]
NSWorkspaceLaunchInhibitingBackgroundOnly: Literal[128]
NSWorkspaceLaunchWithoutAddingToRecents: Literal[256]
NSWorkspaceLaunchWithoutActivation: Literal[512]
NSWorkspaceLaunchDefault: Literal[65536]
NSWorkspaceLaunchAsync: Literal[65536]
NSWorkspaceLaunchAllowingClassicStartup: Literal[131072]
NSWorkspaceLaunchPreferringClassic: Literal[262144]
NSWorkspaceLaunchNewInstance: Literal[524288]
NSWorkspaceLaunchAndHide: Literal[1048576]
NSWorkspaceLaunchAndHideOthers: Literal[2097152]

class NSRunningApplication(Protocol):
    @classmethod
    def currentApplication(cls) -> NSRunningApplication: ...
    @classmethod
    def runningApplicationsWithBundleIdentifier_(cls, bundle: str) -> list[NSRunningApplication]: ...
    def localizedName(self) -> str | None: ...
    def bundleIdentifier(self) -> str | None: ...
    def bundleURL(self) -> NSURL | None: ...
    def executableURL(self) -> NSURL | None: ...
    def launchDate(self) -> NSDate | None: ...
    def processIdentifier(self) -> int: ...
    def isActive(self) -> bool: ...
    def isHidden(self) -> bool: ...
    def isFinishedLaunching(self) -> bool: ...
    def ownsMenuBar(self) -> bool: ...
    def activationPolicy(self) -> int: ...
    def activateWithOptions_(self, options: int) -> bool: ...
    def hide(self) -> bool: ...
    def unhide(self) -> bool: ...
    def terminate(self) -> bool: ...
    def forceTerminate(self) -> bool: ...

class NSWorkspaceOpenConfiguration(Protocol):
    @classmethod
    def alloc(cls) -> NSWorkspaceOpenConfiguration: ...
    @classmethod
    def configuration(cls) -> NSWorkspaceOpenConfiguration: ...
    def init(self) -> NSWorkspaceOpenConfiguration: ...
    def activates(self) -> bool: ...
    def setActivates_(self, flag: bool) -> None: ...
    def createsNewApplicationInstance(self) -> bool: ...
    def setCreatesNewApplicationInstance_(self, flag: bool) -> None: ...
    def hides(self) -> bool: ...
    def setHides_(self, flag: bool) -> None: ...
    def hidesOthers(self) -> bool: ...
    def setHidesOthers_(self, flag: bool) -> None: ...
    def addsToRecentItems(self) -> bool: ...
    def setAddsToRecentItems_(self, flag: bool) -> None: ...
    def allowsRunningApplicationSubstitution(self) -> bool: ...
    def setAllowsRunningApplicationSubstitution_(self, flag: bool) -> None: ...
    def arguments(self) -> list[str]: ...
    def setArguments_(self, arguments: Sequence[str]) -> None: ...
    def environment(self) -> dict[str, str]: ...
    def setEnvironment_(self, environment: Mapping[str, str]) -> None: ...

class NSWorkspace(Protocol):
    @classmethod
    def sharedWorkspace(cls) -> NSWorkspace: ...
    def launchApplication_(self, name: str) -> bool: ...
    def launchAppWithBundleIdentifier_options_additionalEventParamDescriptor_launchIdentifier_(
        self, bundle: str, options: int, descriptor: NSAppleEventDescriptor | None, launch_identifier: None
    ) -> tuple[bool, NSWorkspaceLaunchIdentifier | None]: ...
    def activeApplication(self) -> NSWorkspaceApplicationInfo | None: ...
    def launchedApplications(self) -> list[NSWorkspaceApplicationInfo]: ...
    def runningApplications(self) -> list[NSRunningApplication]: ...
    def frontmostApplication(self) -> NSRunningApplication | None: ...
    def menuBarOwningApplication(self) -> NSRunningApplication | None: ...
    def hideOtherApplications(self) -> None: ...
    def openURL_(self, url: NSURL) -> bool: ...
    def openURL_configuration_completionHandler_(
        self,
        url: NSURL,
        configuration: NSWorkspaceOpenConfiguration,
        completion_handler: Callable[[NSRunningApplication | None, NSError | None], None] | None,
    ) -> None: ...
    def openFile_(self, filepath: str) -> bool: ...
    def openFile_withApplication_(self, filepath: str, app_name: str) -> bool: ...
    def openFile_withApplication_andDeactivate_(self, filepath: str, app_name: str, deactivate: bool) -> bool: ...
    def openTempFile_(self, filepath: str) -> bool: ...
    def activateFileViewerSelectingURLs_(self, urls: Sequence[NSURL]) -> None: ...
    def selectFile_inFileViewerRootedAtPath_(self, filepath: str | None, root_path: str) -> bool: ...
    def fullPathForApplication_(self, app_name: str) -> str | None: ...
    def isFilePackageAtPath_(self, filepath: str) -> bool: ...
    def URLForApplicationWithBundleIdentifier_(self, bundle: str) -> NSURL | None: ...
    def URLsForApplicationsWithBundleIdentifier_(self, bundle: str) -> list[NSURL]: ...
    def URLForApplicationToOpenURL_(self, url: NSURL) -> NSURL | None: ...
    def URLsForApplicationsToOpenURL_(self, url: NSURL) -> list[NSURL]: ...
    def URLForApplicationToOpenContentType_(self, content_type: UTType) -> NSURL | None: ...
    def URLsForApplicationsToOpenContentType_(self, content_type: UTType) -> list[NSURL]: ...
    def openApplicationAtURL_configuration_completionHandler_(
        self,
        application_url: NSURL,
        configuration: NSWorkspaceOpenConfiguration,
        completion_handler: Callable[[NSRunningApplication | None, NSError | None], None] | None,
    ) -> None: ...
    def openURLs_withApplicationAtURL_configuration_completionHandler_(
        self,
        urls: Sequence[NSURL],
        application_url: NSURL,
        configuration: NSWorkspaceOpenConfiguration,
        completion_handler: Callable[[NSRunningApplication | None, NSError | None], None] | None,
    ) -> None: ...
    def setDefaultApplicationAtURL_toOpenURLsWithScheme_completionHandler_(
        self, application_url: NSURL, scheme: str, completion_handler: Callable[[NSError | None], None] | None
    ) -> None: ...
    def getInfoForFile_application_type_(
        self, filepath: str, application: None, file_type: None
    ) -> tuple[bool, str | None, str | None]: ...
    def getFileSystemInfoForPath_isRemovable_isWritable_isUnmountable_description_type_(
        self,
        path: str,
        is_removable: None,
        is_writable: None,
        is_unmountable: None,
        description: None,
        file_system_type: None,
    ) -> tuple[bool, bool, bool, bool, str | None, str | None]: ...

# --- ApplicationServices constants/functions for AX UI automation ---
def AXIsProcessTrusted() -> bool: ...
def AXIsProcessTrustedWithOptions(options: Mapping[str, bool]) -> bool: ...
def AXUIElementCreateApplication(pid: int) -> AXUIElement: ...
def AXUIElementCreateSystemWide() -> AXUIElement: ...
def AXUIElementGetPid(element: AXUIElement, pid: None) -> tuple[AXError, int]: ...
def AXUIElementCopyActionNames(element: AXUIElement, names: None) -> tuple[AXError, list[AXAction] | None]: ...
def AXUIElementCopyActionDescription(
    element: AXUIElement, action: AXAction, description: None
) -> tuple[AXError, str | None]: ...
def AXUIElementCopyAttributeNames(element: AXUIElement, names: None) -> tuple[AXError, list[AXAttribute] | None]: ...
def AXUIElementCopyAttributeValue(
    element: AXUIElement, attribute: AXAttribute, value: None
) -> tuple[AXError, object]: ...
def AXUIElementCopyParameterizedAttributeNames(
    element: AXUIElement, names: None
) -> tuple[AXError, list[AXAttribute] | None]: ...
def AXUIElementCopyParameterizedAttributeValue(
    element: AXUIElement, parameterized_attribute: AXAttribute, parameter: object, value: None
) -> tuple[AXError, object]: ...
def AXUIElementIsAttributeSettable(
    element: AXUIElement, attribute: AXAttribute, settable: None
) -> tuple[AXError, bool]: ...
def AXUIElementSetAttributeValue(element: AXUIElement, attribute: AXAttribute, value: object) -> AXError: ...
def AXUIElementPerformAction(element: AXUIElement, action: AXAction) -> AXError: ...

kAXTrustedCheckOptionPrompt: Literal["AXTrustedCheckOptionPrompt"]

kAXErrorSuccess: Literal[0]
kAXErrorFailure: Literal[-25200]
kAXErrorIllegalArgument: Literal[-25201]
kAXErrorInvalidUIElement: Literal[-25202]
kAXErrorInvalidUIElementObserver: Literal[-25203]
kAXErrorCannotComplete: Literal[-25204]
kAXErrorAttributeUnsupported: Literal[-25205]
kAXErrorActionUnsupported: Literal[-25206]
kAXErrorNotificationUnsupported: Literal[-25207]
kAXErrorNotImplemented: Literal[-25208]
kAXErrorNotificationAlreadyRegistered: Literal[-25209]
kAXErrorNotificationNotRegistered: Literal[-25210]
kAXErrorAPIDisabled: Literal[-25211]
kAXErrorNoValue: Literal[-25212]
kAXErrorParameterizedAttributeUnsupported: Literal[-25213]

kAXChildrenAttribute: Literal["AXChildren"]
kAXCloseButtonAttribute: Literal["AXCloseButton"]
kAXColumnsAttribute: Literal["AXColumns"]
kAXContentsAttribute: Literal["AXContents"]
kAXDescriptionAttribute: Literal["AXDescription"]
kAXEnabledAttribute: Literal["AXEnabled"]
kAXFocusedApplicationAttribute: Literal["AXFocusedApplication"]
kAXFocusedUIElementAttribute: Literal["AXFocusedUIElement"]
kAXFocusedWindowAttribute: Literal["AXFocusedWindow"]
kAXFullScreenButtonAttribute: Literal["AXFullScreenButton"]
kAXIdentifierAttribute: Literal["AXIdentifier"]
kAXMainWindowAttribute: Literal["AXMainWindow"]
kAXMenuBarAttribute: Literal["AXMenuBar"]
kAXMinimizeButtonAttribute: Literal["AXMinimizeButton"]
kAXParentAttribute: Literal["AXParent"]
kAXPositionAttribute: Literal["AXPosition"]
kAXRoleAttribute: Literal["AXRole"]
kAXRoleDescriptionAttribute: Literal["AXRoleDescription"]
kAXRowsAttribute: Literal["AXRows"]
kAXSelectedAttribute: Literal["AXSelected"]
kAXSelectedChildrenAttribute: Literal["AXSelectedChildren"]
kAXSizeAttribute: Literal["AXSize"]
kAXSubroleAttribute: Literal["AXSubrole"]
kAXTabsAttribute: Literal["AXTabs"]
kAXTitleAttribute: Literal["AXTitle"]
kAXValueAttribute: Literal["AXValue"]
kAXVisibleChildrenAttribute: Literal["AXVisibleChildren"]
kAXWindowAttribute: Literal["AXWindow"]
kAXWindowsAttribute: Literal["AXWindows"]

kAXApplicationRole: Literal["AXApplication"]
kAXButtonRole: Literal["AXButton"]
kAXCheckBoxRole: Literal["AXCheckBox"]
kAXColumnRole: Literal["AXColumn"]
kAXGroupRole: Literal["AXGroup"]
kAXListRole: Literal["AXList"]
kAXMenuBarRole: Literal["AXMenuBar"]
kAXMenuBarItemRole: Literal["AXMenuBarItem"]
kAXMenuItemRole: Literal["AXMenuItem"]
kAXPopUpButtonRole: Literal["AXPopUpButton"]
kAXRadioButtonRole: Literal["AXRadioButton"]
kAXRowRole: Literal["AXRow"]
kAXScrollAreaRole: Literal["AXScrollArea"]
kAXScrollBarRole: Literal["AXScrollBar"]
kAXSheetRole: Literal["AXSheet"]
kAXStaticTextRole: Literal["AXStaticText"]
kAXSystemWideRole: Literal["AXSystemWide"]
kAXTableRole: Literal["AXTable"]
kAXTextFieldRole: Literal["AXTextField"]
kAXWindowRole: Literal["AXWindow"]

kAXConfirmAction: Literal["AXConfirm"]
kAXDecrementAction: Literal["AXDecrement"]
kAXIncrementAction: Literal["AXIncrement"]
kAXPressAction: Literal["AXPress"]
kAXRaiseAction: Literal["AXRaise"]
kAXShowMenuAction: Literal["AXShowMenu"]

# --- Module protocols for the lazily-resolved PyObjC framework modules ---
# Each lists exactly the attributes the runtime shim pulls from that module.

class ObjcModule(Protocol):
    autorelease_pool: type[autorelease_pool]

class FoundationModule(Protocol):
    NSDate: type[NSDate]
    NSDefaultRunLoopMode: Literal["kCFRunLoopDefaultMode"]
    NSURL: type[NSURL]
    NSAppleEventDescriptor: type[NSAppleEventDescriptor]
    NSAppleScript: type[NSAppleScript]
    NSRunLoop: type[NSRunLoop]
    NSRunLoopCommonModes: Literal["kCFRunLoopCommonModes"]
    NSPort: type[NSPort]
    NSTimer: type[NSTimer]
    NSBundle: type[NSBundle]

class AppKitModule(Protocol):
    NSWorkspace: type[NSWorkspace]
    NSWorkspaceOpenConfiguration: type[NSWorkspaceOpenConfiguration]
    NSRunningApplication: type[NSRunningApplication]
    NSApplicationActivateAllWindows: Literal[1]
    @property
    @deprecated("Use NSApplicationActivateAllWindows instead")
    def NSApplicationActivateIgnoringOtherApps(self) -> Literal[2]: ...
    NSWorkspaceLaunchAndPrint: Literal[2]
    NSWorkspaceLaunchWithErrorPresentation: Literal[64]
    NSWorkspaceLaunchInhibitingBackgroundOnly: Literal[128]
    NSWorkspaceLaunchWithoutAddingToRecents: Literal[256]
    NSWorkspaceLaunchWithoutActivation: Literal[512]
    NSWorkspaceLaunchDefault: Literal[65536]
    NSWorkspaceLaunchAsync: Literal[65536]
    NSWorkspaceLaunchAllowingClassicStartup: Literal[131072]
    NSWorkspaceLaunchPreferringClassic: Literal[262144]
    NSWorkspaceLaunchNewInstance: Literal[524288]
    NSWorkspaceLaunchAndHide: Literal[1048576]
    NSWorkspaceLaunchAndHideOthers: Literal[2097152]

class ApplicationServicesModule(Protocol):
    def AXIsProcessTrusted(self) -> bool: ...
    def AXIsProcessTrustedWithOptions(self, options: Mapping[str, bool]) -> bool: ...
    def AXUIElementCreateApplication(self, pid: int) -> AXUIElement: ...
    def AXUIElementCreateSystemWide(self) -> AXUIElement: ...
    def AXUIElementGetPid(self, element: AXUIElement, pid: None) -> tuple[AXError, int]: ...
    def AXUIElementCopyActionNames(
        self, element: AXUIElement, names: None
    ) -> tuple[AXError, list[AXAction] | None]: ...
    def AXUIElementCopyActionDescription(
        self, element: AXUIElement, action: AXAction, description: None
    ) -> tuple[AXError, str | None]: ...
    def AXUIElementCopyAttributeNames(
        self, element: AXUIElement, names: None
    ) -> tuple[AXError, list[AXAttribute] | None]: ...
    def AXUIElementCopyAttributeValue(
        self, element: AXUIElement, attribute: AXAttribute, value: None
    ) -> tuple[AXError, object]: ...
    def AXUIElementCopyParameterizedAttributeNames(
        self, element: AXUIElement, names: None
    ) -> tuple[AXError, list[AXAttribute] | None]: ...
    def AXUIElementCopyParameterizedAttributeValue(
        self, element: AXUIElement, parameterized_attribute: AXAttribute, parameter: object, value: None
    ) -> tuple[AXError, object]: ...
    def AXUIElementIsAttributeSettable(
        self, element: AXUIElement, attribute: AXAttribute, settable: None
    ) -> tuple[AXError, bool]: ...
    def AXUIElementSetAttributeValue(self, element: AXUIElement, attribute: AXAttribute, value: object) -> AXError: ...
    def AXUIElementPerformAction(self, element: AXUIElement, action: AXAction) -> AXError: ...

    kAXTrustedCheckOptionPrompt: Literal["AXTrustedCheckOptionPrompt"]

    kAXErrorSuccess: Literal[0]
    kAXErrorFailure: Literal[-25200]
    kAXErrorIllegalArgument: Literal[-25201]
    kAXErrorInvalidUIElement: Literal[-25202]
    kAXErrorInvalidUIElementObserver: Literal[-25203]
    kAXErrorCannotComplete: Literal[-25204]
    kAXErrorAttributeUnsupported: Literal[-25205]
    kAXErrorActionUnsupported: Literal[-25206]
    kAXErrorNotificationUnsupported: Literal[-25207]
    kAXErrorNotImplemented: Literal[-25208]
    kAXErrorNotificationAlreadyRegistered: Literal[-25209]
    kAXErrorNotificationNotRegistered: Literal[-25210]
    kAXErrorAPIDisabled: Literal[-25211]
    kAXErrorNoValue: Literal[-25212]
    kAXErrorParameterizedAttributeUnsupported: Literal[-25213]

    kAXChildrenAttribute: Literal["AXChildren"]
    kAXCloseButtonAttribute: Literal["AXCloseButton"]
    kAXColumnsAttribute: Literal["AXColumns"]
    kAXContentsAttribute: Literal["AXContents"]
    kAXDescriptionAttribute: Literal["AXDescription"]
    kAXEnabledAttribute: Literal["AXEnabled"]
    kAXFocusedApplicationAttribute: Literal["AXFocusedApplication"]
    kAXFocusedUIElementAttribute: Literal["AXFocusedUIElement"]
    kAXFocusedWindowAttribute: Literal["AXFocusedWindow"]
    kAXFullScreenButtonAttribute: Literal["AXFullScreenButton"]
    kAXIdentifierAttribute: Literal["AXIdentifier"]
    kAXMainWindowAttribute: Literal["AXMainWindow"]
    kAXMenuBarAttribute: Literal["AXMenuBar"]
    kAXMinimizeButtonAttribute: Literal["AXMinimizeButton"]
    kAXParentAttribute: Literal["AXParent"]
    kAXPositionAttribute: Literal["AXPosition"]
    kAXRoleAttribute: Literal["AXRole"]
    kAXRoleDescriptionAttribute: Literal["AXRoleDescription"]
    kAXRowsAttribute: Literal["AXRows"]
    kAXSelectedAttribute: Literal["AXSelected"]
    kAXSelectedChildrenAttribute: Literal["AXSelectedChildren"]
    kAXSizeAttribute: Literal["AXSize"]
    kAXSubroleAttribute: Literal["AXSubrole"]
    kAXTabsAttribute: Literal["AXTabs"]
    kAXTitleAttribute: Literal["AXTitle"]
    kAXValueAttribute: Literal["AXValue"]
    kAXVisibleChildrenAttribute: Literal["AXVisibleChildren"]
    kAXWindowAttribute: Literal["AXWindow"]
    kAXWindowsAttribute: Literal["AXWindows"]

    kAXApplicationRole: Literal["AXApplication"]
    kAXButtonRole: Literal["AXButton"]
    kAXCheckBoxRole: Literal["AXCheckBox"]
    kAXColumnRole: Literal["AXColumn"]
    kAXGroupRole: Literal["AXGroup"]
    kAXListRole: Literal["AXList"]
    kAXMenuBarRole: Literal["AXMenuBar"]
    kAXMenuBarItemRole: Literal["AXMenuBarItem"]
    kAXMenuItemRole: Literal["AXMenuItem"]
    kAXPopUpButtonRole: Literal["AXPopUpButton"]
    kAXRadioButtonRole: Literal["AXRadioButton"]
    kAXRowRole: Literal["AXRow"]
    kAXScrollAreaRole: Literal["AXScrollArea"]
    kAXScrollBarRole: Literal["AXScrollBar"]
    kAXSheetRole: Literal["AXSheet"]
    kAXStaticTextRole: Literal["AXStaticText"]
    kAXSystemWideRole: Literal["AXSystemWide"]
    kAXTableRole: Literal["AXTable"]
    kAXTextFieldRole: Literal["AXTextField"]
    kAXWindowRole: Literal["AXWindow"]

    kAXConfirmAction: Literal["AXConfirm"]
    kAXDecrementAction: Literal["AXDecrement"]
    kAXIncrementAction: Literal["AXIncrement"]
    kAXPressAction: Literal["AXPress"]
    kAXRaiseAction: Literal["AXRaise"]
    kAXShowMenuAction: Literal["AXShowMenu"]
