from __future__ import annotations

import os
import shlex
import tempfile
from pathlib import Path

from .._logging import PrettyLog


log = PrettyLog.get_logger(__name__)


class MarkedCommand:
    """Creates synthetic iTerm2 shell-integration marks for non-shell-integrated shells."""

    LEGACY_BEFORE_PROMPT = r"\e]133;A\a"
    LEGACY_AFTER_PROMPT = r"\e]133;B\a"
    LEGACY_BEFORE_OUTPUT = r"\e]133;C\a"
    LEGACY_AFTER_OUTPUT = r"\e]133;D;%d\a"

    BEFORE_PROMPT = r"\e]133;A;aid={aid}\a"
    AFTER_PROMPT = r"\e]133;B;aid={aid}\a"
    BEFORE_OUTPUT = r"\e]133;C;aid={aid}\a"
    AFTER_OUTPUT = r"\e]133;D;%d;aid={aid}\a"

    def __init__(self, command: str, *, command_label: str | None = None, prompt: str = "iterm2-api-wrapper> ") -> None:
        self.command = command
        self.label = command if command_label is None else command_label
        self.prompt = prompt

        self.aid = f"iterm2-api-wrapper-{os.getpid()}-{id(self):x}"
        self.script_path = Path(tempfile.gettempdir()) / f"iterm2_marked_{os.getpid()}_{id(self)}.zsh"
        self.source_command = f"source {shlex.quote(str(self.script_path))}"
        self._closed = False

        self._generate_script()

    @property
    def before_prompt_mark(self) -> str:
        return self.BEFORE_PROMPT.format(aid=self.aid)

    @property
    def after_prompt_mark(self) -> str:
        return self.AFTER_PROMPT.format(aid=self.aid)

    @property
    def before_output_mark(self) -> str:
        return self.BEFORE_OUTPUT.format(aid=self.aid)

    @property
    def after_output_mark(self) -> str:
        return self.AFTER_OUTPUT.format(aid=self.aid)

    @property
    def execution_label(self) -> str:
        return shlex.quote(self.label)

    @property
    def execution_prompt(self) -> str:
        return f"{self.before_prompt_mark}{self.prompt}{self.after_prompt_mark}"

    @property
    def script_body(self) -> str:
        before_prompt = shlex.quote(self.execution_prompt)
        before_output = shlex.quote(self.before_output_mark)
        after_output = shlex.quote(self.after_output_mark)
        return "\n".join(
            (
                "# Generated by iterm2-api-wrapper. Safe to delete.",
                "emulate -L zsh",
                "setopt local_traps",
                "local __iterm_status=0",
                f"printf {before_prompt}",
                f"printf '%s\\n' {self.execution_label}",
                f"printf {before_output}",
                "{",
                f"  {self.command}",
                "} always {",
                "  __iterm_status=$?",
                f'  printf {after_output} "$__iterm_status"',
                "}",
                'return "$__iterm_status"',
                "",
            )
        )

    def _generate_script(self) -> None:
        """Write a marked command script to a local temp file."""
        self.script_path.write_text(self.script_body, encoding="utf-8")
        self.script_path.chmod(0o600)

    def cleanup(self) -> None:
        """Best-effort cleanup for the generated marked command script."""
        if self._closed:
            return

        self._closed = True
        try:
            self.script_path.unlink(missing_ok=True)
        except OSError:
            log.error("Failed to remove marked command script", {"script_path": str(self.script_path)})

    def __enter__(self) -> MarkedCommand:
        return self

    def __exit__(self, _exc_type: object, _exc: object, _tb: object) -> None:
        self.cleanup()

    def __del__(self) -> None:
        """Safety net only. Deterministic cleanup should happen via context manager."""
        self.cleanup()

    def __str__(self) -> str:
        return self.source_command

    def __repr__(self) -> str:
        return (
            f"MarkedCommand(command={self.command!r}, label={self.label!r}, prompt={self.prompt!r}, aid={self.aid!r})"
        )
